# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\"\xff\x01\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1f\n\x05items\x18\x03 \x03(\x0b\x32\x10.order.OrderItem\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x02\x12\"\n\x06status\x18\x05 \x01(\x0e\x32\x12.order.OrderStatus\x12\x18\n\x10shipping_address\x18\x06 \x01(\t\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*T\n\x0bOrderStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\x0b\n\x07SHIPPED\x10\x02\x12\r\n\tDELIVERED\x10\x03\x12\x0c\n\x08\x43\x41NCELED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERSTATUS']._serialized_start=401
  _globals['_ORDERSTATUS']._serialized_end=485
  _globals['_ORDERITEM']._serialized_start=55
  _globals['_ORDERITEM']._serialized_end=141
  _globals['_ORDER']._serialized_start=144
  _globals['_ORDER']._serialized_end=399
# @@protoc_insertion_point(module_scope)
