# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\x85\x01\n\x0bPaymentForm\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x13\n\x0btotal_price\x18\x02 \x01(\x01\x12\x19\n\x11payment_method_id\x18\x03 \x01(\t\x12\x34\n\x0f\x61\x64vance_payment\x18\x04 \x01(\x0b\x32\x1b.payment.AdvancePaymentForm\"N\n\x12\x41\x64vancePaymentForm\x12\x15\n\radvance_price\x18\x01 \x01(\x01\x12!\n\x19\x61\x64vance_payment_method_id\x18\x02 \x01(\t\"M\n\x15RemainingPaymentModel\x12\x19\n\x11payment_method_id\x18\x01 \x01(\t\x12\x19\n\x11remaining_balance\x18\x02 \x01(\x01*V\n\rPaymentStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\x0b\n\x07SHIPPED\x10\x02\x12\r\n\tDELIVERED\x10\x03\x12\x0c\n\x08\x43\x41NCELED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTSTATUS']._serialized_start=321
  _globals['_PAYMENTSTATUS']._serialized_end=407
  _globals['_PAYMENTFORM']._serialized_start=27
  _globals['_PAYMENTFORM']._serialized_end=160
  _globals['_ADVANCEPAYMENTFORM']._serialized_start=162
  _globals['_ADVANCEPAYMENTFORM']._serialized_end=240
  _globals['_REMAININGPAYMENTMODEL']._serialized_start=242
  _globals['_REMAININGPAYMENTMODEL']._serialized_end=319
# @@protoc_insertion_point(module_scope)
